//! Shared CT-e sample for integration tests.
#![allow(dead_code)]

use fiscal_cte::types::*;

pub fn sample_cte() -> CteBuildData {
    CteBuildData {
        ide: Ide {
            c_uf: "43".into(),
            cfop: "5353".into(),
            nat_op: "PRESTACAO DE SERVICO DE TRANSPORTE".into(),
            serie: 1,
            n_ct: 1,
            dh_emi: "2026-06-05T10:00:00-03:00".parse().unwrap(),
            tp_imp: "1".into(),
            tp_emis: "1".into(),
            tp_amb: "2".into(),
            tp_cte: "0".into(),
            proc_emi: None,
            ver_proc: None,
            ind_globalizado: None,
            c_mun_env: "4314902".into(),
            x_mun_env: "PORTO ALEGRE".into(),
            uf_env: "RS".into(),
            modal: "01".into(),
            tp_serv: "0".into(),
            c_mun_ini: "4314902".into(),
            x_mun_ini: "PORTO ALEGRE".into(),
            uf_ini: "RS".into(),
            c_mun_fim: "3550308".into(),
            x_mun_fim: "SAO PAULO".into(),
            uf_fim: "SP".into(),
            retira: "0".into(),
            x_det_retira: None,
            ind_ie_toma: "1".into(),
            toma: Tomador::Toma3 { toma: "0".into() },
        },
        compl: Some(Compl {
            x_obs: Some("Teste de homologacao".into()),
            ..Default::default()
        }),
        emit: Emit {
            doc: Documento::Cnpj("12345678000190".into()),
            ie: Some("1234567890".into()),
            iest: None,
            x_nome: "TRANSPORTADORA TESTE LTDA".into(),
            x_fant: Some("TESTE LOG".into()),
            ender_emit: Endereco {
                x_lgr: "AV TESTE".into(),
                nro: "1000".into(),
                x_cpl: None,
                x_bairro: "CENTRO".into(),
                c_mun: "4314902".into(),
                x_mun: "PORTO ALEGRE".into(),
                cep: Some("90000000".into()),
                uf: "RS".into(),
                c_pais: None,
                x_pais: None,
                fone: Some("5133334444".into()),
            },
            crt: "3".into(),
        },
        rem: Some(Party {
            doc: Documento::Cnpj("11222333000181".into()),
            ie: Some("9988776655".into()),
            x_nome: "REMETENTE TESTE SA".into(),
            x_fant: None,
            fone: None,
            isuf: None,
            ender: Endereco {
                x_lgr: "RUA A".into(),
                nro: "10".into(),
                x_cpl: None,
                x_bairro: "BAIRRO A".into(),
                c_mun: "4314902".into(),
                x_mun: "PORTO ALEGRE".into(),
                cep: Some("90000111".into()),
                uf: "RS".into(),
                c_pais: Some("1058".into()),
                x_pais: Some("BRASIL".into()),
                fone: None,
            },
            email: None,
        }),
        exped: None,
        receb: None,
        dest: Some(Party {
            doc: Documento::Cnpj("44555666000172".into()),
            ie: Some("1122334455".into()),
            x_nome: "DESTINATARIO TESTE SA".into(),
            x_fant: None,
            fone: None,
            isuf: None,
            ender: Endereco {
                x_lgr: "RUA B".into(),
                nro: "20".into(),
                x_cpl: None,
                x_bairro: "BAIRRO B".into(),
                c_mun: "3550308".into(),
                x_mun: "SAO PAULO".into(),
                cep: Some("01000000".into()),
                uf: "SP".into(),
                c_pais: Some("1058".into()),
                x_pais: Some("BRASIL".into()),
                fone: None,
            },
            email: None,
        }),
        v_prest: VPrest {
            v_t_prest: "1500.00".into(),
            v_rec: "1500.00".into(),
            comp: vec![Componente {
                x_nome: "FRETE PESO".into(),
                v_comp: "1500.00".into(),
            }],
        },
        imp: Imp {
            icms: Icms::Icms00 {
                v_bc: "1500.00".into(),
                p_icms: "12.00".into(),
                v_icms: "180.00".into(),
            },
            v_tot_trib: None,
            inf_ad_fisco: None,
        },
        inf_cte_norm: InfCteNorm {
            inf_carga: InfCarga {
                v_carga: Some("50000.00".into()),
                pro_pred: "DIVERSOS".into(),
                x_out_cat: None,
                inf_q: vec![InfQ {
                    c_unid: "01".into(),
                    tp_med: "PESO BRUTO".into(),
                    q_carga: "1000.0000".into(),
                }],
                v_carga_averb: None,
            },
            inf_doc: Some(InfDoc {
                inf_nfe: vec![InfNfe {
                    chave: "4".repeat(44),
                    d_prev: None,
                }],
                inf_outros: vec![],
            }),
            inf_modal: InfModal {
                versao_modal: "4.00".into(),
                modal: Modal::Rodo(RodoCte {
                    rntrc: "12345678".into(),
                    inf_ciot: vec![],
                    vale_ped: vec![],
                }),
            },
            inf_cte_sub: None,
            seg: vec![],
        },
        inf_cte_comp: vec![],
        aut_xml: vec![],
        inf_resp_tec: None,
        emit_cnpj: "12345678000190".into(),
        numeric_code: Some("00000001".into()),
    }
}

pub fn sample_cteos() -> fiscal_cte::types_os::CteOsBuildData {
    use fiscal_cte::types_os::*;
    let ender = || Endereco {
        x_lgr: "RUA A".into(),
        nro: "10".into(),
        x_cpl: None,
        x_bairro: "CENTRO".into(),
        c_mun: "3550308".into(),
        x_mun: "SAO PAULO".into(),
        cep: Some("01001000".into()),
        uf: "SP".into(),
        c_pais: Some("1058".into()),
        x_pais: Some("BRASIL".into()),
        fone: None,
    };
    CteOsBuildData {
        numeric_code: Some("00000001".into()),
        emit_cnpj: "12345678000190".into(),
        ide: IdeOs {
            c_uf: "35".into(),
            cfop: "5357".into(),
            nat_op: "TRANSPORTE DE PESSOAS".into(),
            serie: 1,
            n_ct: 1,
            dh_emi: "2026-06-06T10:00:00-03:00".parse().unwrap(),
            tp_imp: "1".into(),
            tp_emis: "1".into(),
            tp_amb: "2".into(),
            tp_cte: "0".into(),
            proc_emi: None,
            ver_proc: None,
            c_mun_env: "3550308".into(),
            x_mun_env: "SAO PAULO".into(),
            uf_env: "SP".into(),
            modal: "01".into(),
            tp_serv: "6".into(),
            ind_ie_toma: "9".into(),
            c_mun_ini: "3550308".into(),
            x_mun_ini: "SAO PAULO".into(),
            uf_ini: "SP".into(),
            c_mun_fim: "3509502".into(),
            x_mun_fim: "CAMPINAS".into(),
            uf_fim: "SP".into(),
            inf_percurso: vec![],
            dh_cont: None,
            x_just: None,
        },
        compl: None,
        emit: Emit {
            doc: Documento::Cnpj("12345678000190".into()),
            ie: Some("111111111111".into()),
            iest: None,
            x_nome: "TRANSP TESTE".into(),
            x_fant: None,
            ender_emit: ender(),
            crt: "3".into(),
        },
        toma: TomaOs {
            doc: Documento::Cpf("34493536837".into()),
            ie: None,
            x_nome: "FULANO DE TAL".into(),
            x_fant: None,
            fone: None,
            ender_toma: ender(),
            email: None,
        },
        v_prest: VPrest {
            v_t_prest: "100.00".into(),
            v_rec: "100.00".into(),
            comp: vec![Componente {
                x_nome: "SERVICO".into(),
                v_comp: "100.00".into(),
            }],
        },
        imp: Imp {
            icms: Icms::IcmsSn { ind_sn: "1".into() },
            v_tot_trib: None,
            inf_ad_fisco: None,
        },
        inf_cte_norm: InfCteNormOs {
            inf_servico: InfServico {
                x_desc_serv: "TRANSPORTE DE PESSOAS".into(),
                q_carga: None,
            },
            inf_doc_ref: vec![],
            seg: vec![],
            inf_modal: InfModalOs {
                versao_modal: "4.00".into(),
                rodo_os: RodoOs {
                    taf: Some("123456789".into()),
                    nro_reg_estadual: None,
                    veic: None,
                    inf_fretamento: None,
                },
            },
        },
        aut_xml: vec![],
        inf_resp_tec: None,
    }
}

pub fn sample_gtve() -> fiscal_cte::types_gtve::GtveBuildData {
    use fiscal_cte::types_gtve::*;
    use fiscal_cte::types_os::TomaOs;
    let ender = || Endereco {
        x_lgr: "RUA A".into(),
        nro: "10".into(),
        x_cpl: None,
        x_bairro: "CENTRO".into(),
        c_mun: "3550308".into(),
        x_mun: "SAO PAULO".into(),
        cep: Some("01001000".into()),
        uf: "SP".into(),
        c_pais: Some("1058".into()),
        x_pais: Some("BRASIL".into()),
        fone: None,
    };
    let party = |nome: &str| Party {
        doc: Documento::Cnpj("11222333000181".into()),
        ie: Some("111111111".into()),
        x_nome: nome.into(),
        x_fant: None,
        fone: None,
        isuf: None,
        ender: ender(),
        email: None,
    };
    GtveBuildData {
        numeric_code: Some("00000001".into()),
        emit_cnpj: "12345678000190".into(),
        ide: IdeGtve {
            c_uf: "35".into(),
            cfop: "5359".into(),
            nat_op: "TRANSPORTE DE VALORES".into(),
            serie: 1,
            n_ct: 1,
            dh_emi: "2026-06-06T10:00:00-03:00".parse().unwrap(),
            tp_imp: "1".into(),
            tp_emis: "1".into(),
            tp_amb: "2".into(),
            tp_cte: "4".into(),
            ver_proc: None,
            c_mun_env: "3550308".into(),
            x_mun_env: "SAO PAULO".into(),
            uf_env: "SP".into(),
            modal: "01".into(),
            tp_serv: "9".into(),
            ind_ie_toma: "9".into(),
            dh_saida_orig: "2026-06-06T09:00:00-03:00".into(),
            dh_chegada_dest: "2026-06-06T18:00:00-03:00".into(),
            toma: TomaOs {
                doc: Documento::Cpf("34493536837".into()),
                ie: None,
                x_nome: "FULANO".into(),
                x_fant: None,
                fone: None,
                ender_toma: ender(),
                email: None,
            },
        },
        compl: None,
        emit: Emit {
            doc: Documento::Cnpj("12345678000190".into()),
            ie: Some("111111111111".into()),
            iest: None,
            x_nome: "TRANSP VALORES".into(),
            x_fant: None,
            ender_emit: ender(),
            crt: "3".into(),
        },
        rem: party("REMETENTE"),
        dest: party("DESTINATARIO"),
        origem: Some(ender()),
        destino: Some(ender()),
        det_gtv: DetGtv {
            inf_especie: vec![InfEspecie {
                tp_especie: "1".into(),
                v_especie: "1000.00".into(),
                tp_numerario: Some("1".into()),
                x_moeda_estr: None,
            }],
            q_carga: "1000.0000".into(),
            inf_veiculo: vec![InfVeiculoGtv {
                placa: "ABC1234".into(),
                uf: "SP".into(),
                rntrc: Some("12345678".into()),
            }],
        },
        aut_xml: vec![],
        inf_resp_tec: None,
    }
}
